name: carrier_info_plus_example
description: Demonstrates carrier_info_plus.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  carrier_info_plus:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
