// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.moulibheemaneti.carrier_info_plus

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Pigeon equivalent of [SimState]. */
enum class PlatformSimState(val raw: Int) {
  UNKNOWN(0),
  ABSENT(1),
  PIN_REQUIRED(2),
  PUK_REQUIRED(3),
  NETWORK_LOCKED(4),
  READY(5),
  NOT_READY(6),
  PERMANENTLY_DISABLED(7),
  CARD_IO_ERROR(8),
  CARD_RESTRICTED(9);

  companion object {
    fun ofRaw(raw: Int): PlatformSimState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Pigeon equivalent of [RadioAccessTechnology].
 *
 * The mapping from a radio technology to a network generation is deliberately
 * absent here: it is pure derivation, so it lives in Dart where both platforms
 * get the same answer and it can be tested without a device.
 */
enum class PlatformRadioAccessTechnology(val raw: Int) {
  UNKNOWN(0),
  GPRS(1),
  EDGE(2),
  GSM(3),
  ONE_XRTT(4),
  CDMA(5),
  IDEN(6),
  UMTS(7),
  HSDPA(8),
  HSUPA(9),
  HSPA(10),
  HSPAP(11),
  EVDO0(12),
  EVDO_A(13),
  EVDO_B(14),
  EHRPD(15),
  TD_SCDMA(16),
  LTE(17),
  LTE_CA(18),
  IWLAN(19),
  NR(20);

  companion object {
    fun ofRaw(raw: Int): PlatformRadioAccessTechnology? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Pigeon equivalent of [CellularDataState]. */
enum class PlatformCellularDataState(val raw: Int) {
  UNKNOWN(0),
  RESTRICTED(1),
  NOT_RESTRICTED(2);

  companion object {
    fun ofRaw(raw: Int): PlatformCellularDataState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Pigeon equivalent of [DataLimitation]. */
enum class PlatformDataLimitation(val raw: Int) {
  NONE(0),
  PERMISSION_NOT_GRANTED(1),
  PLATFORM_REMOVED_API(2),
  NO_TELEPHONY_HARDWARE(3);

  companion object {
    fun ofRaw(raw: Int): PlatformDataLimitation? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Pigeon equivalent of [SimCard].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformSimCard (
  /**
   * Android's stable per-subscription identifier. Null on iOS, and null on
   * Android when read without the per-SIM permission.
   */
  val subscriptionId: Long? = null,
  /** Physical or logical slot. Null when the SIM could not be enumerated. */
  val slotIndex: Long? = null,
  val carrierName: String? = null,
  val displayName: String? = null,
  val mobileCountryCode: String? = null,
  val mobileNetworkCode: String? = null,
  val countryIso: String? = null,
  val carrierId: Long? = null,
  val isEmbedded: Boolean,
  val isRoaming: Boolean,
  val simState: PlatformSimState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformSimCard {
      val subscriptionId = pigeonVar_list[0] as Long?
      val slotIndex = pigeonVar_list[1] as Long?
      val carrierName = pigeonVar_list[2] as String?
      val displayName = pigeonVar_list[3] as String?
      val mobileCountryCode = pigeonVar_list[4] as String?
      val mobileNetworkCode = pigeonVar_list[5] as String?
      val countryIso = pigeonVar_list[6] as String?
      val carrierId = pigeonVar_list[7] as Long?
      val isEmbedded = pigeonVar_list[8] as Boolean
      val isRoaming = pigeonVar_list[9] as Boolean
      val simState = pigeonVar_list[10] as PlatformSimState
      return PlatformSimCard(subscriptionId, slotIndex, carrierName, displayName, mobileCountryCode, mobileNetworkCode, countryIso, carrierId, isEmbedded, isRoaming, simState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subscriptionId,
      slotIndex,
      carrierName,
      displayName,
      mobileCountryCode,
      mobileNetworkCode,
      countryIso,
      carrierId,
      isEmbedded,
      isRoaming,
      simState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformSimCard
    return MessagesPigeonUtils.deepEquals(this.subscriptionId, other.subscriptionId) && MessagesPigeonUtils.deepEquals(this.slotIndex, other.slotIndex) && MessagesPigeonUtils.deepEquals(this.carrierName, other.carrierName) && MessagesPigeonUtils.deepEquals(this.displayName, other.displayName) && MessagesPigeonUtils.deepEquals(this.mobileCountryCode, other.mobileCountryCode) && MessagesPigeonUtils.deepEquals(this.mobileNetworkCode, other.mobileNetworkCode) && MessagesPigeonUtils.deepEquals(this.countryIso, other.countryIso) && MessagesPigeonUtils.deepEquals(this.carrierId, other.carrierId) && MessagesPigeonUtils.deepEquals(this.isEmbedded, other.isEmbedded) && MessagesPigeonUtils.deepEquals(this.isRoaming, other.isRoaming) && MessagesPigeonUtils.deepEquals(this.simState, other.simState)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subscriptionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.slotIndex)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.carrierName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mobileCountryCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mobileNetworkCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.countryIso)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.carrierId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isEmbedded)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isRoaming)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.simState)
    return result
  }
  override fun toString(): String {
    return "PlatformSimCard(subscriptionId=$subscriptionId, slotIndex=$slotIndex, carrierName=$carrierName, displayName=$displayName, mobileCountryCode=$mobileCountryCode, mobileNetworkCode=$mobileNetworkCode, countryIso=$countryIso, carrierId=$carrierId, isEmbedded=$isEmbedded, isRoaming=$isRoaming, simState=$simState)"
  }
}

/**
 * Pigeon equivalent of [TelephonyCapabilities].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformTelephonyCapabilities (
  val isVoiceCapable: Boolean,
  val isSmsCapable: Boolean,
  val isDataCapable: Boolean,
  val isDataEnabled: Boolean,
  val isMultiSimSupported: Boolean,
  val supportsEmbeddedSim: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformTelephonyCapabilities {
      val isVoiceCapable = pigeonVar_list[0] as Boolean
      val isSmsCapable = pigeonVar_list[1] as Boolean
      val isDataCapable = pigeonVar_list[2] as Boolean
      val isDataEnabled = pigeonVar_list[3] as Boolean
      val isMultiSimSupported = pigeonVar_list[4] as Boolean
      val supportsEmbeddedSim = pigeonVar_list[5] as Boolean
      return PlatformTelephonyCapabilities(isVoiceCapable, isSmsCapable, isDataCapable, isDataEnabled, isMultiSimSupported, supportsEmbeddedSim)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isVoiceCapable,
      isSmsCapable,
      isDataCapable,
      isDataEnabled,
      isMultiSimSupported,
      supportsEmbeddedSim,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformTelephonyCapabilities
    return MessagesPigeonUtils.deepEquals(this.isVoiceCapable, other.isVoiceCapable) && MessagesPigeonUtils.deepEquals(this.isSmsCapable, other.isSmsCapable) && MessagesPigeonUtils.deepEquals(this.isDataCapable, other.isDataCapable) && MessagesPigeonUtils.deepEquals(this.isDataEnabled, other.isDataEnabled) && MessagesPigeonUtils.deepEquals(this.isMultiSimSupported, other.isMultiSimSupported) && MessagesPigeonUtils.deepEquals(this.supportsEmbeddedSim, other.supportsEmbeddedSim)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isVoiceCapable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isSmsCapable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isDataCapable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isDataEnabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isMultiSimSupported)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.supportsEmbeddedSim)
    return result
  }
  override fun toString(): String {
    return "PlatformTelephonyCapabilities(isVoiceCapable=$isVoiceCapable, isSmsCapable=$isSmsCapable, isDataCapable=$isDataCapable, isDataEnabled=$isDataEnabled, isMultiSimSupported=$isMultiSimSupported, supportsEmbeddedSim=$supportsEmbeddedSim)"
  }
}

/**
 * Pigeon equivalent of [NetworkInfo].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformNetworkInfo (
  /** One entry per active data subscription. Empty when nothing is readable. */
  val radioTechnologies: List<PlatformRadioAccessTechnology>,
  val operatorName: String? = null,
  val countryIso: String? = null,
  val cellularDataState: PlatformCellularDataState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformNetworkInfo {
      val radioTechnologies = pigeonVar_list[0] as List<PlatformRadioAccessTechnology>
      val operatorName = pigeonVar_list[1] as String?
      val countryIso = pigeonVar_list[2] as String?
      val cellularDataState = pigeonVar_list[3] as PlatformCellularDataState
      return PlatformNetworkInfo(radioTechnologies, operatorName, countryIso, cellularDataState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      radioTechnologies,
      operatorName,
      countryIso,
      cellularDataState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformNetworkInfo
    return MessagesPigeonUtils.deepEquals(this.radioTechnologies, other.radioTechnologies) && MessagesPigeonUtils.deepEquals(this.operatorName, other.operatorName) && MessagesPigeonUtils.deepEquals(this.countryIso, other.countryIso) && MessagesPigeonUtils.deepEquals(this.cellularDataState, other.cellularDataState)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.radioTechnologies)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.operatorName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.countryIso)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cellularDataState)
    return result
  }
  override fun toString(): String {
    return "PlatformNetworkInfo(radioTechnologies=$radioTechnologies, operatorName=$operatorName, countryIso=$countryIso, cellularDataState=$cellularDataState)"
  }
}

/**
 * Pigeon equivalent of [PlatformSupport].
 *
 * Named with an `Info` suffix because the public model is already called
 * `PlatformSupport`; the usual `Platform` prefix would produce
 * `PlatformPlatformSupport`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformSupportInfo (
  /** Whether carrier name, MCC, MNC and country could be read at all. */
  val carrierIdentityAvailable: Boolean,
  /** Whether every SIM could be enumerated, rather than just the active one. */
  val perSimDataAvailable: Boolean,
  val permissionGranted: Boolean,
  /**
   * Why anything above is false. This is the field that tells an app whether
   * to prompt or to hide the UI.
   */
  val limitation: PlatformDataLimitation
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformSupportInfo {
      val carrierIdentityAvailable = pigeonVar_list[0] as Boolean
      val perSimDataAvailable = pigeonVar_list[1] as Boolean
      val permissionGranted = pigeonVar_list[2] as Boolean
      val limitation = pigeonVar_list[3] as PlatformDataLimitation
      return PlatformSupportInfo(carrierIdentityAvailable, perSimDataAvailable, permissionGranted, limitation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      carrierIdentityAvailable,
      perSimDataAvailable,
      permissionGranted,
      limitation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformSupportInfo
    return MessagesPigeonUtils.deepEquals(this.carrierIdentityAvailable, other.carrierIdentityAvailable) && MessagesPigeonUtils.deepEquals(this.perSimDataAvailable, other.perSimDataAvailable) && MessagesPigeonUtils.deepEquals(this.permissionGranted, other.permissionGranted) && MessagesPigeonUtils.deepEquals(this.limitation, other.limitation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.carrierIdentityAvailable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.perSimDataAvailable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.permissionGranted)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.limitation)
    return result
  }
  override fun toString(): String {
    return "PlatformSupportInfo(carrierIdentityAvailable=$carrierIdentityAvailable, perSimDataAvailable=$perSimDataAvailable, permissionGranted=$permissionGranted, limitation=$limitation)"
  }
}

/**
 * Pigeon equivalent of [CarrierInfo].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformCarrierInfo (
  val simCards: List<PlatformSimCard>,
  val capabilities: PlatformTelephonyCapabilities,
  val network: PlatformNetworkInfo,
  val support: PlatformSupportInfo
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCarrierInfo {
      val simCards = pigeonVar_list[0] as List<PlatformSimCard>
      val capabilities = pigeonVar_list[1] as PlatformTelephonyCapabilities
      val network = pigeonVar_list[2] as PlatformNetworkInfo
      val support = pigeonVar_list[3] as PlatformSupportInfo
      return PlatformCarrierInfo(simCards, capabilities, network, support)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      simCards,
      capabilities,
      network,
      support,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformCarrierInfo
    return MessagesPigeonUtils.deepEquals(this.simCards, other.simCards) && MessagesPigeonUtils.deepEquals(this.capabilities, other.capabilities) && MessagesPigeonUtils.deepEquals(this.network, other.network) && MessagesPigeonUtils.deepEquals(this.support, other.support)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.simCards)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.capabilities)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.network)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.support)
    return result
  }
  override fun toString(): String {
    return "PlatformCarrierInfo(simCards=$simCards, capabilities=$capabilities, network=$network, support=$support)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformSimState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformRadioAccessTechnology.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformCellularDataState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformDataLimitation.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformSimCard.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformTelephonyCapabilities.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformNetworkInfo.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformSupportInfo.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCarrierInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformSimState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformRadioAccessTechnology -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformCellularDataState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformDataLimitation -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformSimCard -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PlatformTelephonyCapabilities -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PlatformNetworkInfo -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PlatformSupportInfo -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PlatformCarrierInfo -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Calls into the host platform.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CarrierInfoApi {
  /**
   * Reads a fresh snapshot of the device's cellular state.
   *
   * Never throws for missing data: anything unreadable comes back null and is
   * explained through [PlatformCarrierInfo.support].
   */
  fun getCarrierInfo(): PlatformCarrierInfo
  /**
   * Whether the permission guarding per-SIM data has been granted.
   *
   * Always true on iOS, which has no equivalent permission.
   */
  fun hasPermission(): Boolean
  /**
   * Prompts for the permission guarding per-SIM data.
   *
   * Asynchronous because Android answers through an activity callback rather
   * than a return value.
   */
  suspend fun requestPermission(): Boolean

  companion object {
    /** The codec used by CarrierInfoApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CarrierInfoApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CarrierInfoApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.getCarrierInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCarrierInfo())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.hasPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasPermission())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestPermission())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
