// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Pigeon equivalent of [SimState].
enum PlatformSimState {
  unknown,
  absent,
  pinRequired,
  pukRequired,
  networkLocked,
  ready,
  notReady,
  permanentlyDisabled,
  cardIoError,
  cardRestricted,
}

/// Pigeon equivalent of [RadioAccessTechnology].
///
/// The mapping from a radio technology to a network generation is deliberately
/// absent here: it is pure derivation, so it lives in Dart where both platforms
/// get the same answer and it can be tested without a device.
enum PlatformRadioAccessTechnology {
  unknown,
  gprs,
  edge,
  gsm,
  oneXrtt,
  cdma,
  iden,
  umts,
  hsdpa,
  hsupa,
  hspa,
  hspap,
  evdo0,
  evdoA,
  evdoB,
  ehrpd,
  tdScdma,
  lte,
  lteCa,
  iwlan,
  nr,
}

/// Pigeon equivalent of [CellularDataState].
enum PlatformCellularDataState { unknown, restricted, notRestricted }

/// Pigeon equivalent of [DataLimitation].
enum PlatformDataLimitation {
  none,
  permissionNotGranted,
  platformRemovedApi,
  noTelephonyHardware,
}

/// Pigeon equivalent of [SimCard].
class PlatformSimCard {
  PlatformSimCard({
    this.subscriptionId,
    this.slotIndex,
    this.carrierName,
    this.displayName,
    this.mobileCountryCode,
    this.mobileNetworkCode,
    this.countryIso,
    this.carrierId,
    required this.isEmbedded,
    required this.isRoaming,
    required this.simState,
  });

  /// Android's stable per-subscription identifier. Null on iOS, and null on
  /// Android when read without the per-SIM permission.
  int? subscriptionId;

  /// Physical or logical slot. Null when the SIM could not be enumerated.
  int? slotIndex;

  String? carrierName;

  String? displayName;

  String? mobileCountryCode;

  String? mobileNetworkCode;

  String? countryIso;

  int? carrierId;

  bool isEmbedded;

  bool isRoaming;

  PlatformSimState simState;

  List<Object?> _toList() {
    return <Object?>[
      subscriptionId,
      slotIndex,
      carrierName,
      displayName,
      mobileCountryCode,
      mobileNetworkCode,
      countryIso,
      carrierId,
      isEmbedded,
      isRoaming,
      simState,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformSimCard decode(Object result) {
    result as List<Object?>;
    return PlatformSimCard(
      subscriptionId: result[0] as int?,
      slotIndex: result[1] as int?,
      carrierName: result[2] as String?,
      displayName: result[3] as String?,
      mobileCountryCode: result[4] as String?,
      mobileNetworkCode: result[5] as String?,
      countryIso: result[6] as String?,
      carrierId: result[7] as int?,
      isEmbedded: result[8]! as bool,
      isRoaming: result[9]! as bool,
      simState: result[10]! as PlatformSimState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSimCard || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(subscriptionId, other.subscriptionId) &&
        _deepEquals(slotIndex, other.slotIndex) &&
        _deepEquals(carrierName, other.carrierName) &&
        _deepEquals(displayName, other.displayName) &&
        _deepEquals(mobileCountryCode, other.mobileCountryCode) &&
        _deepEquals(mobileNetworkCode, other.mobileNetworkCode) &&
        _deepEquals(countryIso, other.countryIso) &&
        _deepEquals(carrierId, other.carrierId) &&
        _deepEquals(isEmbedded, other.isEmbedded) &&
        _deepEquals(isRoaming, other.isRoaming) &&
        _deepEquals(simState, other.simState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSimCard(subscriptionId: $subscriptionId, slotIndex: $slotIndex, carrierName: $carrierName, displayName: $displayName, mobileCountryCode: $mobileCountryCode, mobileNetworkCode: $mobileNetworkCode, countryIso: $countryIso, carrierId: $carrierId, isEmbedded: $isEmbedded, isRoaming: $isRoaming, simState: $simState)';
  }
}

/// Pigeon equivalent of [TelephonyCapabilities].
class PlatformTelephonyCapabilities {
  PlatformTelephonyCapabilities({
    required this.isVoiceCapable,
    required this.isSmsCapable,
    required this.isDataCapable,
    required this.isDataEnabled,
    required this.isMultiSimSupported,
    required this.supportsEmbeddedSim,
  });

  bool isVoiceCapable;

  bool isSmsCapable;

  bool isDataCapable;

  bool isDataEnabled;

  bool isMultiSimSupported;

  bool supportsEmbeddedSim;

  List<Object?> _toList() {
    return <Object?>[
      isVoiceCapable,
      isSmsCapable,
      isDataCapable,
      isDataEnabled,
      isMultiSimSupported,
      supportsEmbeddedSim,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformTelephonyCapabilities decode(Object result) {
    result as List<Object?>;
    return PlatformTelephonyCapabilities(
      isVoiceCapable: result[0]! as bool,
      isSmsCapable: result[1]! as bool,
      isDataCapable: result[2]! as bool,
      isDataEnabled: result[3]! as bool,
      isMultiSimSupported: result[4]! as bool,
      supportsEmbeddedSim: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformTelephonyCapabilities ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isVoiceCapable, other.isVoiceCapable) &&
        _deepEquals(isSmsCapable, other.isSmsCapable) &&
        _deepEquals(isDataCapable, other.isDataCapable) &&
        _deepEquals(isDataEnabled, other.isDataEnabled) &&
        _deepEquals(isMultiSimSupported, other.isMultiSimSupported) &&
        _deepEquals(supportsEmbeddedSim, other.supportsEmbeddedSim);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformTelephonyCapabilities(isVoiceCapable: $isVoiceCapable, isSmsCapable: $isSmsCapable, isDataCapable: $isDataCapable, isDataEnabled: $isDataEnabled, isMultiSimSupported: $isMultiSimSupported, supportsEmbeddedSim: $supportsEmbeddedSim)';
  }
}

/// Pigeon equivalent of [NetworkInfo].
class PlatformNetworkInfo {
  PlatformNetworkInfo({
    required this.radioTechnologies,
    this.operatorName,
    this.countryIso,
    required this.cellularDataState,
  });

  /// One entry per active data subscription. Empty when nothing is readable.
  List<PlatformRadioAccessTechnology> radioTechnologies;

  String? operatorName;

  String? countryIso;

  PlatformCellularDataState cellularDataState;

  List<Object?> _toList() {
    return <Object?>[
      radioTechnologies,
      operatorName,
      countryIso,
      cellularDataState,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformNetworkInfo decode(Object result) {
    result as List<Object?>;
    return PlatformNetworkInfo(
      radioTechnologies: (result[0]! as List<Object?>)
          .cast<PlatformRadioAccessTechnology>(),
      operatorName: result[1] as String?,
      countryIso: result[2] as String?,
      cellularDataState: result[3]! as PlatformCellularDataState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformNetworkInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(radioTechnologies, other.radioTechnologies) &&
        _deepEquals(operatorName, other.operatorName) &&
        _deepEquals(countryIso, other.countryIso) &&
        _deepEquals(cellularDataState, other.cellularDataState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformNetworkInfo(radioTechnologies: $radioTechnologies, operatorName: $operatorName, countryIso: $countryIso, cellularDataState: $cellularDataState)';
  }
}

/// Pigeon equivalent of [PlatformSupport].
///
/// Named with an `Info` suffix because the public model is already called
/// `PlatformSupport`; the usual `Platform` prefix would produce
/// `PlatformPlatformSupport`.
class PlatformSupportInfo {
  PlatformSupportInfo({
    required this.carrierIdentityAvailable,
    required this.perSimDataAvailable,
    required this.permissionGranted,
    required this.limitation,
  });

  /// Whether carrier name, MCC, MNC and country could be read at all.
  bool carrierIdentityAvailable;

  /// Whether every SIM could be enumerated, rather than just the active one.
  bool perSimDataAvailable;

  bool permissionGranted;

  /// Why anything above is false. This is the field that tells an app whether
  /// to prompt or to hide the UI.
  PlatformDataLimitation limitation;

  List<Object?> _toList() {
    return <Object?>[
      carrierIdentityAvailable,
      perSimDataAvailable,
      permissionGranted,
      limitation,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformSupportInfo decode(Object result) {
    result as List<Object?>;
    return PlatformSupportInfo(
      carrierIdentityAvailable: result[0]! as bool,
      perSimDataAvailable: result[1]! as bool,
      permissionGranted: result[2]! as bool,
      limitation: result[3]! as PlatformDataLimitation,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSupportInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(
          carrierIdentityAvailable,
          other.carrierIdentityAvailable,
        ) &&
        _deepEquals(perSimDataAvailable, other.perSimDataAvailable) &&
        _deepEquals(permissionGranted, other.permissionGranted) &&
        _deepEquals(limitation, other.limitation);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSupportInfo(carrierIdentityAvailable: $carrierIdentityAvailable, perSimDataAvailable: $perSimDataAvailable, permissionGranted: $permissionGranted, limitation: $limitation)';
  }
}

/// Pigeon equivalent of [CarrierInfo].
class PlatformCarrierInfo {
  PlatformCarrierInfo({
    required this.simCards,
    required this.capabilities,
    required this.network,
    required this.support,
  });

  List<PlatformSimCard> simCards;

  PlatformTelephonyCapabilities capabilities;

  PlatformNetworkInfo network;

  PlatformSupportInfo support;

  List<Object?> _toList() {
    return <Object?>[simCards, capabilities, network, support];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCarrierInfo decode(Object result) {
    result as List<Object?>;
    return PlatformCarrierInfo(
      simCards: (result[0]! as List<Object?>).cast<PlatformSimCard>(),
      capabilities: result[1]! as PlatformTelephonyCapabilities,
      network: result[2]! as PlatformNetworkInfo,
      support: result[3]! as PlatformSupportInfo,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCarrierInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(simCards, other.simCards) &&
        _deepEquals(capabilities, other.capabilities) &&
        _deepEquals(network, other.network) &&
        _deepEquals(support, other.support);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCarrierInfo(simCards: $simCards, capabilities: $capabilities, network: $network, support: $support)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformSimState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformRadioAccessTechnology) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformCellularDataState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PlatformDataLimitation) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is PlatformSimCard) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PlatformTelephonyCapabilities) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PlatformNetworkInfo) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PlatformSupportInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCarrierInfo) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformSimState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : PlatformRadioAccessTechnology.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformCellularDataState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformDataLimitation.values[value];
      case 133:
        return PlatformSimCard.decode(readValue(buffer)!);
      case 134:
        return PlatformTelephonyCapabilities.decode(readValue(buffer)!);
      case 135:
        return PlatformNetworkInfo.decode(readValue(buffer)!);
      case 136:
        return PlatformSupportInfo.decode(readValue(buffer)!);
      case 137:
        return PlatformCarrierInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Calls into the host platform.
class CarrierInfoApi {
  /// Constructor for [CarrierInfoApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CarrierInfoApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Reads a fresh snapshot of the device's cellular state.
  ///
  /// Never throws for missing data: anything unreadable comes back null and is
  /// explained through [PlatformCarrierInfo.support].
  Future<PlatformCarrierInfo> getCarrierInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.getCarrierInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformCarrierInfo;
  }

  /// Whether the permission guarding per-SIM data has been granted.
  ///
  /// Always true on iOS, which has no equivalent permission.
  Future<bool> hasPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.hasPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Prompts for the permission guarding per-SIM data.
  ///
  /// Asynchronous because Android answers through an activity callback rather
  /// than a return value.
  Future<bool> requestPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
