// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Pigeon equivalent of [SimState].
enum PlatformSimState: Int, CaseIterable {
  case unknown = 0
  case absent = 1
  case pinRequired = 2
  case pukRequired = 3
  case networkLocked = 4
  case ready = 5
  case notReady = 6
  case permanentlyDisabled = 7
  case cardIoError = 8
  case cardRestricted = 9
}

/// Pigeon equivalent of [RadioAccessTechnology].
///
/// Values are named after the radio technology itself, not after either
/// platform's constant, because the two disagree on spelling for the same
/// thing. Android sources these from `TelephonyManager.NETWORK_TYPE_*`, iOS
/// from `CTRadioAccessTechnology*`, and neither platform reports every value.
///
/// The mapping from a technology to a network generation is deliberately
/// absent here: it is pure derivation, so it lives in Dart where both
/// platforms get the same answer and it can be tested without a device.
enum PlatformRadioAccessTechnology: Int, CaseIterable {
  /// Nothing readable, or a technology neither platform names.
  case unknown = 0
  /// General Packet Radio Service: 2G packet data.
  ///
  /// Android `NETWORK_TYPE_GPRS`, iOS `CTRadioAccessTechnologyGPRS`.
  case gprs = 1
  /// Enhanced Data rates for GSM Evolution: 2.5G, GPRS with more throughput.
  ///
  /// Android `NETWORK_TYPE_EDGE`, iOS `CTRadioAccessTechnologyEdge`.
  case edge = 2
  /// Global System for Mobile Communications: 2G circuit-switched.
  ///
  /// Android `NETWORK_TYPE_GSM`. Android only -- iOS describes the same
  /// radio through its data technology, GPRS or Edge.
  case gsm = 3
  /// CDMA2000 1x Radio Transmission Technology: 2G data on CDMA networks.
  ///
  /// Android `NETWORK_TYPE_1xRTT`, iOS `CTRadioAccessTechnologyCDMA1x`.
  case oneXrtt = 4
  /// Code Division Multiple Access (IS-95): 2G, effectively retired.
  ///
  /// Android `NETWORK_TYPE_CDMA`. Android only.
  case cdma = 5
  /// Integrated Digital Enhanced Network: Motorola's 2G push-to-talk network.
  ///
  /// Android `NETWORK_TYPE_IDEN`. Android only, and shut down in practice --
  /// present because the constant still exists, not because you will see it.
  case iden = 6
  /// Universal Mobile Telecommunications System: baseline 3G.
  ///
  /// Android `NETWORK_TYPE_UMTS`, iOS `CTRadioAccessTechnologyWCDMA` -- WCDMA
  /// is the air interface UMTS runs over, so the two name the same network.
  case umts = 7
  /// High Speed Downlink Packet Access: 3.5G, faster downlink.
  ///
  /// Android `NETWORK_TYPE_HSDPA`, iOS `CTRadioAccessTechnologyHSDPA`.
  case hsdpa = 8
  /// High Speed Uplink Packet Access: 3.5G, faster uplink.
  ///
  /// Android `NETWORK_TYPE_HSUPA`, iOS `CTRadioAccessTechnologyHSUPA`.
  case hsupa = 9
  /// High Speed Packet Access: HSDPA and HSUPA reported together.
  ///
  /// Android `NETWORK_TYPE_HSPA`. Android only -- iOS reports the two halves
  /// separately and never combines them.
  case hspa = 10
  /// Evolved HSPA, marketed as HSPA+: 3.75G.
  ///
  /// Android `NETWORK_TYPE_HSPAP`. Android only.
  case hspap = 11
  /// CDMA2000 EV-DO Revision 0: first-generation 3G data on CDMA.
  ///
  /// Android `NETWORK_TYPE_EVDO_0`, iOS `CTRadioAccessTechnologyCDMAEVDORev0`.
  case evdo0 = 12
  /// EV-DO Revision A: Revision 0 with a usable uplink.
  ///
  /// Android `NETWORK_TYPE_EVDO_A`, iOS `CTRadioAccessTechnologyCDMAEVDORevA`.
  case evdoA = 13
  /// EV-DO Revision B: multi-carrier EV-DO.
  ///
  /// Android `NETWORK_TYPE_EVDO_B`, iOS `CTRadioAccessTechnologyCDMAEVDORevB`.
  case evdoB = 14
  /// Evolved High Rate Packet Data: the bridge that let CDMA carriers reach
  /// LTE without a hard cutover.
  ///
  /// Android `NETWORK_TYPE_EHRPD`, iOS `CTRadioAccessTechnologyeHRPD`.
  case ehrpd = 15
  /// Time Division Synchronous CDMA: 3G, deployed almost entirely in China.
  ///
  /// Android `NETWORK_TYPE_TD_SCDMA`. Android only.
  case tdScdma = 16
  /// Long Term Evolution: 4G.
  ///
  /// Android `NETWORK_TYPE_LTE`, iOS `CTRadioAccessTechnologyLTE`.
  case lte = 17
  /// Wi-Fi calling: voice and data over IEEE 802.11 rather than a cellular
  /// radio.
  ///
  /// Android `NETWORK_TYPE_IWLAN`. Android only. Note that this is not a
  /// cellular generation at all, so it derives to an unknown generation
  /// rather than to 4G or 5G -- the device is on Wi-Fi, not on a mobile
  /// network, and treating it as either would misreport the connection.
  case iwlan = 18
  /// 5G New Radio, standalone: a 5G core with a 5G radio.
  ///
  /// Android `NETWORK_TYPE_NR`, iOS `CTRadioAccessTechnologyNR`.
  case nr = 19
  /// 5G New Radio, non-standalone: a 5G radio anchored to a 4G core, which is
  /// how most "5G" coverage is actually deployed.
  ///
  /// iOS `CTRadioAccessTechnologyNRNSA`. iOS only: Android does not give NSA
  /// its own network type, reporting it as [lte] plus a separate NR state,
  /// so an Android device on non-standalone 5G comes back as [lte] here.
  case nrNsa = 20
}

/// Pigeon equivalent of [CellularDataState].
enum PlatformCellularDataState: Int, CaseIterable {
  case unknown = 0
  case restricted = 1
  case notRestricted = 2
}

/// Pigeon equivalent of [DataLimitation].
enum PlatformDataLimitation: Int, CaseIterable {
  case none = 0
  case permissionNotGranted = 1
  case platformRemovedApi = 2
  case noTelephonyHardware = 3
}

/// Pigeon equivalent of [SimCard].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformSimCard: Hashable, CustomStringConvertible {
  /// Android's stable per-subscription identifier. Null on iOS, and null on
  /// Android when read without the per-SIM permission.
  var subscriptionId: Int64? = nil
  /// Physical or logical slot. Null when the SIM could not be enumerated.
  var slotIndex: Int64? = nil
  var carrierName: String? = nil
  var displayName: String? = nil
  var mobileCountryCode: String? = nil
  var mobileNetworkCode: String? = nil
  var countryIso: String? = nil
  var carrierId: Int64? = nil
  var isEmbedded: Bool
  var isRoaming: Bool
  var simState: PlatformSimState
  /// Whether this is the subscription mobile data runs over.
  ///
  /// Android resolves this from `SubscriptionManager.getDefaultDataSubscriptionId()`,
  /// which is API 24 and needs no runtime permission, so it is answerable even
  /// when the SIM list itself is not. Without that permission only one SIM is
  /// enumerated and it is the default one by construction, so the flag is
  /// still correct.
  ///
  /// Always false on iOS, which exposes no notion of a default line.
  var isDefaultData: Bool
  /// Whether this is the subscription calls are placed over.
  ///
  /// The same caveats as [isDefaultData]; Android reads
  /// `SubscriptionManager.getDefaultVoiceSubscriptionId()`. On a dual-SIM
  /// device this is routinely a different SIM from the data one, which is
  /// exactly why picking "the first SIM" is not good enough.
  var isDefaultVoice: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformSimCard? {
    let subscriptionId: Int64? = nilOrValue(pigeonVar_list[0])
    let slotIndex: Int64? = nilOrValue(pigeonVar_list[1])
    let carrierName: String? = nilOrValue(pigeonVar_list[2])
    let displayName: String? = nilOrValue(pigeonVar_list[3])
    let mobileCountryCode: String? = nilOrValue(pigeonVar_list[4])
    let mobileNetworkCode: String? = nilOrValue(pigeonVar_list[5])
    let countryIso: String? = nilOrValue(pigeonVar_list[6])
    let carrierId: Int64? = nilOrValue(pigeonVar_list[7])
    let isEmbedded = pigeonVar_list[8] as! Bool
    let isRoaming = pigeonVar_list[9] as! Bool
    let simState = pigeonVar_list[10] as! PlatformSimState
    let isDefaultData = pigeonVar_list[11] as! Bool
    let isDefaultVoice = pigeonVar_list[12] as! Bool

    return PlatformSimCard(
      subscriptionId: subscriptionId,
      slotIndex: slotIndex,
      carrierName: carrierName,
      displayName: displayName,
      mobileCountryCode: mobileCountryCode,
      mobileNetworkCode: mobileNetworkCode,
      countryIso: countryIso,
      carrierId: carrierId,
      isEmbedded: isEmbedded,
      isRoaming: isRoaming,
      simState: simState,
      isDefaultData: isDefaultData,
      isDefaultVoice: isDefaultVoice
    )
  }
  func toList() -> [Any?] {
    return [
      subscriptionId,
      slotIndex,
      carrierName,
      displayName,
      mobileCountryCode,
      mobileNetworkCode,
      countryIso,
      carrierId,
      isEmbedded,
      isRoaming,
      simState,
      isDefaultData,
      isDefaultVoice,
    ]
  }
  static func == (lhs: PlatformSimCard, rhs: PlatformSimCard) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.subscriptionId, rhs.subscriptionId) && MessagesPigeonInternal.deepEquals(lhs.slotIndex, rhs.slotIndex) && MessagesPigeonInternal.deepEquals(lhs.carrierName, rhs.carrierName) && MessagesPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && MessagesPigeonInternal.deepEquals(lhs.mobileCountryCode, rhs.mobileCountryCode) && MessagesPigeonInternal.deepEquals(lhs.mobileNetworkCode, rhs.mobileNetworkCode) && MessagesPigeonInternal.deepEquals(lhs.countryIso, rhs.countryIso) && MessagesPigeonInternal.deepEquals(lhs.carrierId, rhs.carrierId) && MessagesPigeonInternal.deepEquals(lhs.isEmbedded, rhs.isEmbedded) && MessagesPigeonInternal.deepEquals(lhs.isRoaming, rhs.isRoaming) && MessagesPigeonInternal.deepEquals(lhs.simState, rhs.simState) && MessagesPigeonInternal.deepEquals(lhs.isDefaultData, rhs.isDefaultData) && MessagesPigeonInternal.deepEquals(lhs.isDefaultVoice, rhs.isDefaultVoice)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformSimCard")
    MessagesPigeonInternal.deepHash(value: subscriptionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: slotIndex, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: carrierName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mobileCountryCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mobileNetworkCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: countryIso, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: carrierId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isEmbedded, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isRoaming, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: simState, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDefaultData, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDefaultVoice, hasher: &hasher)
  }

  public var description: String {
    return "PlatformSimCard(subscriptionId: \(String(describing: subscriptionId)), slotIndex: \(String(describing: slotIndex)), carrierName: \(String(describing: carrierName)), displayName: \(String(describing: displayName)), mobileCountryCode: \(String(describing: mobileCountryCode)), mobileNetworkCode: \(String(describing: mobileNetworkCode)), countryIso: \(String(describing: countryIso)), carrierId: \(String(describing: carrierId)), isEmbedded: \(String(describing: isEmbedded)), isRoaming: \(String(describing: isRoaming)), simState: \(String(describing: simState)), isDefaultData: \(String(describing: isDefaultData)), isDefaultVoice: \(String(describing: isDefaultVoice)))"
  }
}

/// Pigeon equivalent of [TelephonyCapabilities].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformTelephonyCapabilities: Hashable, CustomStringConvertible {
  var isVoiceCapable: Bool
  var isSmsCapable: Bool
  var isDataCapable: Bool
  var isDataEnabled: Bool
  var isMultiSimSupported: Bool
  var supportsEmbeddedSim: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformTelephonyCapabilities? {
    let isVoiceCapable = pigeonVar_list[0] as! Bool
    let isSmsCapable = pigeonVar_list[1] as! Bool
    let isDataCapable = pigeonVar_list[2] as! Bool
    let isDataEnabled = pigeonVar_list[3] as! Bool
    let isMultiSimSupported = pigeonVar_list[4] as! Bool
    let supportsEmbeddedSim = pigeonVar_list[5] as! Bool

    return PlatformTelephonyCapabilities(
      isVoiceCapable: isVoiceCapable,
      isSmsCapable: isSmsCapable,
      isDataCapable: isDataCapable,
      isDataEnabled: isDataEnabled,
      isMultiSimSupported: isMultiSimSupported,
      supportsEmbeddedSim: supportsEmbeddedSim
    )
  }
  func toList() -> [Any?] {
    return [
      isVoiceCapable,
      isSmsCapable,
      isDataCapable,
      isDataEnabled,
      isMultiSimSupported,
      supportsEmbeddedSim,
    ]
  }
  static func == (lhs: PlatformTelephonyCapabilities, rhs: PlatformTelephonyCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.isVoiceCapable, rhs.isVoiceCapable) && MessagesPigeonInternal.deepEquals(lhs.isSmsCapable, rhs.isSmsCapable) && MessagesPigeonInternal.deepEquals(lhs.isDataCapable, rhs.isDataCapable) && MessagesPigeonInternal.deepEquals(lhs.isDataEnabled, rhs.isDataEnabled) && MessagesPigeonInternal.deepEquals(lhs.isMultiSimSupported, rhs.isMultiSimSupported) && MessagesPigeonInternal.deepEquals(lhs.supportsEmbeddedSim, rhs.supportsEmbeddedSim)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformTelephonyCapabilities")
    MessagesPigeonInternal.deepHash(value: isVoiceCapable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isSmsCapable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDataCapable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDataEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isMultiSimSupported, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportsEmbeddedSim, hasher: &hasher)
  }

  public var description: String {
    return "PlatformTelephonyCapabilities(isVoiceCapable: \(String(describing: isVoiceCapable)), isSmsCapable: \(String(describing: isSmsCapable)), isDataCapable: \(String(describing: isDataCapable)), isDataEnabled: \(String(describing: isDataEnabled)), isMultiSimSupported: \(String(describing: isMultiSimSupported)), supportsEmbeddedSim: \(String(describing: supportsEmbeddedSim)))"
  }
}

/// Pigeon equivalent of [NetworkInfo].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformNetworkInfo: Hashable, CustomStringConvertible {
  /// The radio technologies currently in use, empty when nothing is readable.
  ///
  /// Deliberately not attributed to a SIM. On a dual-SIM device with two
  /// active data subscriptions there is no reliable way to say which radio
  /// belongs to which SIM across both platforms, and inventing an association
  /// would be worse than omitting one. Treat this as a property of the device,
  /// not of a subscription.
  var radioTechnologies: [PlatformRadioAccessTechnology]
  var operatorName: String? = nil
  var countryIso: String? = nil
  var cellularDataState: PlatformCellularDataState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformNetworkInfo? {
    let radioTechnologies = pigeonVar_list[0] as! [PlatformRadioAccessTechnology]
    let operatorName: String? = nilOrValue(pigeonVar_list[1])
    let countryIso: String? = nilOrValue(pigeonVar_list[2])
    let cellularDataState = pigeonVar_list[3] as! PlatformCellularDataState

    return PlatformNetworkInfo(
      radioTechnologies: radioTechnologies,
      operatorName: operatorName,
      countryIso: countryIso,
      cellularDataState: cellularDataState
    )
  }
  func toList() -> [Any?] {
    return [
      radioTechnologies,
      operatorName,
      countryIso,
      cellularDataState,
    ]
  }
  static func == (lhs: PlatformNetworkInfo, rhs: PlatformNetworkInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.radioTechnologies, rhs.radioTechnologies) && MessagesPigeonInternal.deepEquals(lhs.operatorName, rhs.operatorName) && MessagesPigeonInternal.deepEquals(lhs.countryIso, rhs.countryIso) && MessagesPigeonInternal.deepEquals(lhs.cellularDataState, rhs.cellularDataState)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformNetworkInfo")
    MessagesPigeonInternal.deepHash(value: radioTechnologies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: operatorName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: countryIso, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cellularDataState, hasher: &hasher)
  }

  public var description: String {
    return "PlatformNetworkInfo(radioTechnologies: \(String(describing: radioTechnologies)), operatorName: \(String(describing: operatorName)), countryIso: \(String(describing: countryIso)), cellularDataState: \(String(describing: cellularDataState)))"
  }
}

/// Pigeon equivalent of [PlatformSupport].
///
/// Named with an `Info` suffix because the public model is already called
/// `PlatformSupport`; the usual `Platform` prefix would produce
/// `PlatformPlatformSupport`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformSupportInfo: Hashable, CustomStringConvertible {
  /// Whether carrier name, MCC, MNC and country could be read at all.
  var carrierIdentityAvailable: Bool
  /// Whether every SIM could be enumerated, rather than just the active one.
  var perSimDataAvailable: Bool
  var permissionGranted: Bool
  /// Why anything above is false. This is the field that tells an app whether
  /// to prompt or to hide the UI.
  ///
  /// Deliberately a single value rather than a set. More than one limitation
  /// can technically apply at once -- the iOS Simulator has no telephony
  /// hardware and no granted permission -- but only the most fundamental one is
  /// reported, because it is the one that decides what an app should do. There
  /// is no point prompting for a permission on a device with no radio.
  var limitation: PlatformDataLimitation


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformSupportInfo? {
    let carrierIdentityAvailable = pigeonVar_list[0] as! Bool
    let perSimDataAvailable = pigeonVar_list[1] as! Bool
    let permissionGranted = pigeonVar_list[2] as! Bool
    let limitation = pigeonVar_list[3] as! PlatformDataLimitation

    return PlatformSupportInfo(
      carrierIdentityAvailable: carrierIdentityAvailable,
      perSimDataAvailable: perSimDataAvailable,
      permissionGranted: permissionGranted,
      limitation: limitation
    )
  }
  func toList() -> [Any?] {
    return [
      carrierIdentityAvailable,
      perSimDataAvailable,
      permissionGranted,
      limitation,
    ]
  }
  static func == (lhs: PlatformSupportInfo, rhs: PlatformSupportInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.carrierIdentityAvailable, rhs.carrierIdentityAvailable) && MessagesPigeonInternal.deepEquals(lhs.perSimDataAvailable, rhs.perSimDataAvailable) && MessagesPigeonInternal.deepEquals(lhs.permissionGranted, rhs.permissionGranted) && MessagesPigeonInternal.deepEquals(lhs.limitation, rhs.limitation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformSupportInfo")
    MessagesPigeonInternal.deepHash(value: carrierIdentityAvailable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: perSimDataAvailable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: permissionGranted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: limitation, hasher: &hasher)
  }

  public var description: String {
    return "PlatformSupportInfo(carrierIdentityAvailable: \(String(describing: carrierIdentityAvailable)), perSimDataAvailable: \(String(describing: perSimDataAvailable)), permissionGranted: \(String(describing: permissionGranted)), limitation: \(String(describing: limitation)))"
  }
}

/// Pigeon equivalent of [CarrierInfo].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCarrierInfo: Hashable, CustomStringConvertible {
  /// Every SIM the platform was able to describe.
  ///
  /// This can be shorter than [simCount]: a platform may know a SIM exists
  /// without being able to say anything about it. Compare the two before
  /// concluding a device is single-SIM.
  var simCards: [PlatformSimCard]
  /// How many SIMs the platform says are present, or null when it cannot say.
  ///
  /// Exists because "how many SIMs" and "what are they" are separate questions
  /// with separate answers. iOS 16+ can count the cellular services it has
  /// without reporting anything identifying about them, and Android can
  /// enumerate fully but only once the per-SIM permission is granted -- the
  /// count itself needs that permission too, so it is null without it.
  ///
  /// Prefer this over `simCards.length` when asking whether a device is
  /// dual-SIM.
  var simCount: Int64? = nil
  var capabilities: PlatformTelephonyCapabilities
  var network: PlatformNetworkInfo
  var support: PlatformSupportInfo


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCarrierInfo? {
    let simCards = pigeonVar_list[0] as! [PlatformSimCard]
    let simCount: Int64? = nilOrValue(pigeonVar_list[1])
    let capabilities = pigeonVar_list[2] as! PlatformTelephonyCapabilities
    let network = pigeonVar_list[3] as! PlatformNetworkInfo
    let support = pigeonVar_list[4] as! PlatformSupportInfo

    return PlatformCarrierInfo(
      simCards: simCards,
      simCount: simCount,
      capabilities: capabilities,
      network: network,
      support: support
    )
  }
  func toList() -> [Any?] {
    return [
      simCards,
      simCount,
      capabilities,
      network,
      support,
    ]
  }
  static func == (lhs: PlatformCarrierInfo, rhs: PlatformCarrierInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.simCards, rhs.simCards) && MessagesPigeonInternal.deepEquals(lhs.simCount, rhs.simCount) && MessagesPigeonInternal.deepEquals(lhs.capabilities, rhs.capabilities) && MessagesPigeonInternal.deepEquals(lhs.network, rhs.network) && MessagesPigeonInternal.deepEquals(lhs.support, rhs.support)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCarrierInfo")
    MessagesPigeonInternal.deepHash(value: simCards, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: simCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: capabilities, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: network, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: support, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCarrierInfo(simCards: \(String(describing: simCards)), simCount: \(String(describing: simCount)), capabilities: \(String(describing: capabilities)), network: \(String(describing: network)), support: \(String(describing: support)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformSimState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformRadioAccessTechnology(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformCellularDataState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformDataLimitation(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return PlatformSimCard.fromList(self.readValue() as! [Any?])
    case 134:
      return PlatformTelephonyCapabilities.fromList(self.readValue() as! [Any?])
    case 135:
      return PlatformNetworkInfo.fromList(self.readValue() as! [Any?])
    case 136:
      return PlatformSupportInfo.fromList(self.readValue() as! [Any?])
    case 137:
      return PlatformCarrierInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformSimState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformRadioAccessTechnology {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCellularDataState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformDataLimitation {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformSimCard {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformTelephonyCapabilities {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformNetworkInfo {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformSupportInfo {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCarrierInfo {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Calls into the host platform.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CarrierInfoApi {
  /// Reads a fresh snapshot of the device's cellular state.
  ///
  /// Never throws for missing data: anything unreadable comes back null and is
  /// explained through [PlatformCarrierInfo.support].
  ///
  /// Dispatched to a background thread. The implementation makes roughly
  /// fifteen binder IPC calls into the platform's telephony service, and the
  /// default queue would run all of them on the platform thread -- the host
  /// app's main thread. Each call is usually sub-millisecond, but they are IPC
  /// and can stall, and a carrier lookup has no business sitting in front of
  /// the host app's UI work.
  ///
  /// This does not change anything on the Dart side, which awaits a Future
  /// either way.
  func getCarrierInfo() throws -> PlatformCarrierInfo
  /// Whether the permission guarding per-SIM data has been granted.
  ///
  /// Always true on iOS, which has no equivalent permission.
  func hasPermission() throws -> Bool
  /// Prompts for the permission guarding per-SIM data.
  ///
  /// Asynchronous because Android answers through an activity callback rather
  /// than a return value.
  func requestPermission() async throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CarrierInfoApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CarrierInfoApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CarrierInfoApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    /// Reads a fresh snapshot of the device's cellular state.
    ///
    /// Never throws for missing data: anything unreadable comes back null and is
    /// explained through [PlatformCarrierInfo.support].
    ///
    /// Dispatched to a background thread. The implementation makes roughly
    /// fifteen binder IPC calls into the platform's telephony service, and the
    /// default queue would run all of them on the platform thread -- the host
    /// app's main thread. Each call is usually sub-millisecond, but they are IPC
    /// and can stall, and a carrier lookup has no business sitting in front of
    /// the host app's UI work.
    ///
    /// This does not change anything on the Dart side, which awaits a Future
    /// either way.
    let getCarrierInfoChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.getCarrierInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.getCarrierInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      getCarrierInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCarrierInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCarrierInfoChannel.setMessageHandler(nil)
    }
    /// Whether the permission guarding per-SIM data has been granted.
    ///
    /// Always true on iOS, which has no equivalent permission.
    let hasPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.hasPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasPermission()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasPermissionChannel.setMessageHandler(nil)
    }
    /// Prompts for the permission guarding per-SIM data.
    ///
    /// Asynchronous because Android answers through an activity callback rather
    /// than a return value.
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.carrier_info_plus.CarrierInfoApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestPermission()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
  }
}
